http:
  clients:
    webhook-site:
      base-url: https://webhook.site/f6ec3af8-08d7-427d-b839-3d88f84fa9c0

rabbitmq:
  host: localhost
  port: 5672
  username: user
  password: password
  listeners:
    event:
      queue: webhook
  publishers:
    webhook:
      exchange: outbound
      routingkey: to_outbound_webhook

management:
  endpoint:
    health:
      show-details: always

spring:
  cache:
    type: redis
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false # disables lazy loading in web views, important for performance.
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
        generate_statistics: true
        jdbc:
          # important: When using GenerationType.IDENTITY Hibernate disable batching, you need to use BatchSequenceGenerator
          batch_size: 10
          time_zone: Asia/Shanghai
  devtools:
    restart:
      enabled: false

logging:
  pattern.correlation: "[${spring.application.name:},%X{trace_id:-},%X{span_id:-},%X{trace_flags:-}]"
  level:
    web: info
    org.springframework.cache: TRACE
    hibernate.SQL: DEBUG
    hibernate.engine.jdbc.batch.internal.BatchingBatch: DEBUG
# application.yml
jwt:
  access:
    token:
      validity:
        seconds: 28800 #八小时
  issuer:
    url: http://localhost:8082
