
http:
  clients:
    webhook-site:
      base-url: https://webhook.site/f6ec3af8-08d7-427d-b839-3d88f84fa9c0

rabbitmq:
  host: localhost
  port: 5672
  username: user
  password: password
  listeners:
    event:
      queue: webhook
  publishers:
    webhook:
      exchange: outbound
      routingkey: to_outbound_webhook

management:
  endpoint:
    health:
      show-details: always

  # for testing purpose you can use https://github.com/CtrlSpice/otel-desktop-viewer

spring:
  jpa:
    properties:
      hibernate:
        show_sql: false
        format_sql: false
  devtools:
    restart:
      enabled: false

logging:
  pattern.correlation: "[${spring.application.name:},%X{trace_id:-},%X{span_id:-},%X{trace_flags:-}]"
  level:
    web: info
    # org.springframework.cache: TRACE
    # hibernate.SQL: DEBUG
    # hibernate.engine.jdbc.batch.internal.BatchingBatch: DEBUG
    # reactor.netty.http.client.HttpClient: DEBUG
keycloak:
  realm: api
  server-url: http://127.0.0.1:8080
  client-id: api-cli
  grant-type: password
  name: admin
  password: admin

springdoc:
  swagger-ui:
    oauth:
      client-id: api-cli
      client-secret: l5L20VeolDTjUDinfYjaxZHmzWOPs59G
